import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";


const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doctor Appointment Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="md:px-20">
          {children}
          <Toaster />
        </div>
        <Footer />
      </body>
    </html>
  );
}
